### PR TITLE
stop `console.error`ing on expected errors

### LINKED ISSUE #52: Unexpected Error Logging Despite Handled Exceptions
Hello,

I'm encountering an issue with the `@workos-inc/authkit-js` library where it logs errors to the browser console even though the errors are expected.

image

Specifically, in the code snippet:

https://github.com/workos/authkit-js/blob/5efd97fa980cc33b548171b91049124883e94f98/src/create-client.ts#L108

```typescript
  async initialize() {
    // [...]
      try {
        await this.#refreshSession();
        this.#scheduleAutomaticRefresh();
      } catch {
        // this is expected to fail if a user doesn't
        // have a session. do nothing.
      }
    }
  }
```
It seems like errors are being logged despite the comment indicating that the failure to refresh a session is expected and should be silently ignored. Could you please look into this behavior? It would be great to see the error logging suppressed here unless there's a real issue to address.

Thank you!

### PR DESCRIPTION
**Pull request by cmatheson**
Fixes #52.

Refresh errors are expected to happen (session ends, user is not logged in yet, etc.). This is sometimes useful information when debugging, so we should use `console.debug` instead of `console.error`.

### CODE REVIEW

File: src/create-client.ts [hunk 1]
```diff
@@ -310,8 +313,6 @@ An authorization_code was supplied for a login which did not originate at the ap
           this.#onRefreshFailure &&
           this.#onRefreshFailure({ signIn: this.signIn.bind(this) });
       }
-      // TODO: if a lock couldn't be acquired... that's not a fatal error.
```
Comment (cmatheson) [inline src/create-client.ts:313]: i think this TODO is addressed on L304.

**Review by PaulAsjes — APPROVED** [review]
